version: 0.0
os: linux

files:
  - source: /
    destination: /home/centos

hooks:
  AfterInstall:
   - location: /test.sh
     timeout: 100
     runas: centos
  ApplicationStart:
   - location: /startJar.sh
     timeout: 100
     runas: root
