server:
  port: 8080

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://localhost:3306/csye?characterEncoding=utf-8
    username: root
    password: root


mybatis:
  typeAliasesPackage: edu.neu.xswl.csye6225
  mapperLocations: classpath:mapper/**.xml